# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: Multispectral Pedestrian Detection Challenge
short_description: Detect Pedestrian from RGB(visible-wavelength) and Thermal(LWIR-wavelength) images
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.png
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: Benchmark
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: False
start_date: 2019-01-01 00:00:00
end_date: 2099-05-31 23:59:59
published: True
allowed_email_domains: ["hanyang.ac.kr"]

leaderboard:
  - id: 1
    schema:
      {
        "labels": [
          "MR_-2_iou50_all",
          # "MR_-2_iou60_all",
          # "MR_-2_iou75_all",
          "MR_-2_iou50_day",
          # "MR_-2_iou60_day",
          # "MR_-2_iou75_day",
          "MR_-2_iou50_night",
          # "MR_-2_iou60_night",
          # "MR_-2_iou75_night",
          "AP_iou50",
          "AP_iou75",
          "AP_iou50:95",
        ],
        "default_order_by": "MR_-2_iou50_all",
        "metadata": {
          "MR_-2_iou50_all": {
            "sort_ascending": True,
            "description": "All (Day+Night), Log-averaged Miss Rate at False Positive Per Images in [10^-2, 0]",
          },
          "MR_-2_iou50_day": {
            "sort_ascending": True,
            "description": "All (Day+Night), Log-averaged Miss Rate at False Positive Per Images in [10^-2, 0]",
          },
          "MR_-2_iou50_night": {
            "sort_ascending": True,
            "description": "All (Day+Night), Log-averaged Miss Rate at False Positive Per Images in [10^-2, 0]",
          },
          "AP_iou50": {
            "sort_ascending": True,
            "description": "All (Day+Night), Average Precision (101) @ IoU threshold 0.5",
          },
          "AP_iou75": {
            "sort_ascending": True,
            "description": "All (Day+Night), Average Precision (101) @ IoU threshold 0.75",
          },
          "AP_iou50:95": {
            "sort_ascending": True,
            "description": "All (Day+Night), Average Precision (101) @ IoU threshold 0.5:0.95",
          },
        }
      }

challenge_phases:
  # - id: 1
  #   name: Dev Phase
  #   description: templates/challenge_phase_1_description.html
  #   leaderboard_public: False
  #   is_public: True
  #   is_submission_public: True
  #   start_date: 2019-01-19 00:00:00
  #   end_date: 2099-04-25 23:59:59
  #   test_annotation_file: annotations/KAIST_annotation.json
  #   codename: dev
  #   max_submissions_per_day: 5
  #   max_submissions_per_month: 50
  #   max_submissions: 50
  #   default_submission_meta_attributes:
  #     - name: method_name
  #       is_visible: True
  #     - name: method_description
  #       is_visible: True
  #     - name: project_url
  #       is_visible: True
  #     - name: publication_url
  #       is_visible: True
  #   submission_meta_attributes:
  #     - name: TextAttribute
  #       description: Sample
  #       type: text
  #       required: False
  #     - name: SingleOptionAttribute
  #       description: Sample
  #       type: radio
  #       options: ["A", "B", "C"]
  #     - name: MultipleChoiceAttribute
  #       description: Sample
  #       type: checkbox
  #       options: ["alpha", "beta", "gamma"]
  #     - name: TrueFalseField
  #       description: Sample
  #       type: boolean
  #       required: True
  #   is_restricted_to_select_one_submission: False
  #   is_partial_submission_evaluation_enabled: False
  #   allowed_submission_file_types: ".json, .zip, .txt, .tsv, .gz, .csv, .h5, .npy, .npz"
  - id: 1
    # name: Test Phase
    name: benchmark
    description: templates/challenge_phase_1_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2024-06-11 00:00:00
    end_date: 2024-07-31 23:59:59
    test_annotation_file: annotations/KAIST_annotation.json
    codename: test
    max_submissions_per_day: 100
    max_submissions_per_month: 2000
    max_submissions: 50
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      # - name: publication_url
      #   is_visible: False
    # submission_meta_attributes:
    #   - name: TextAttribute
    #     description: Sample
    #     type: text
    #   - name: SingleOptionAttribute
    #     description: Sample
    #     type: radio
    #     options: ["A", "B", "C"]
    #   - name: MultipleChoiceAttribute
    #     description: Sample
    #     type: checkbox
    #     options: ["alpha", "beta", "gamma"]
    #   - name: TrueFalseField
    #     description: Use extra data
    #     type: boolean
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".json, .txt"

dataset_splits:
  # - id: 1
  #   name: Train Split
  #   codename: train_split
  - id: 1
    name: Test Split
    codename: test_split

challenge_phase_splits:
  # - challenge_phase_id: 1
  #   leaderboard_id: 1
  #   dataset_split_id: 1
  #   visibility: 1
  #   leaderboard_decimal_precision: 4
  #   is_leaderboard_order_descending: True
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 4
    is_leaderboard_order_descending: True
  # - challenge_phase_id: 1
  #   leaderboard_id: 1
  #   dataset_split_id: 2
  #   visibility: 1
  #   leaderboard_decimal_precision: 2
  #   is_leaderboard_order_descending: True
